### PR TITLE
230601112257 static page builder

### PR DESCRIPTION
**Pull request by Vasil-Derilov**
open pull request for tpl-gen refactoring

### CODE REVIEW

**Comment by Vasil-Derilov** [comment]
The issue with pkey_replace and expand path functions not working properly was they were getting passed an empty dict as a second argument hence they were unable to find any values to replace the keys in the path with. pkey_replace was giving and error and expand_path was outputting the files with the %key% syntax. Uncommenting line 106 in convert_utils.py fixed the issue.

**Comment by Vasil-Derilov** [comment]
Tested the creation of directories and files. It creates them when they don't exist.

**Comment by Vasil-Derilov** [comment]
I have added more testing scripts which can be run with 'ORG=csi make do-test-tpl-gen' I will start working on a workflow that can run said tests.

**Comment by Vasil-Derilov** [comment]
Also tested manually not with pytest (I still dont have the tests for that) if the steps render correctly and they seem to be okay folder and file creation also works. We would have 100% coverage once we can test the rendering of steps but this should be done gradually before we can test tpl-gen we should test all the utility functions it uses first.

**Comment by Vasil-Derilov** [comment]
Right now we are at about 40-60% coverage

**Comment by Vasil-Derilov** [comment]
Another note, if we have proper tests defined in pytest eg. ones that simulate the file system of conf projects we don't need to clone the app and conf projects into the workflow itself to run the tests. It would be cleaner to use only tpl-gen for the tests and simulate the rest. I know what you are thinking what if we get unexpected behavior when running the actual step generation. Well if every test passes  and we are exhaustive that would mean the bug isnt in tpl-gen otherwise we would be guessing where the bug is.

**Comment by Vasil-Derilov** [comment]
This workflow seems to do the job for now I know its not how it is supposed to since it runs the tests directly and not through the docker lets just use it for this week and next week I will get to implementing a proper one with the docker and the ORG=csi make do-test-tpl-gen command. Also note that the command works so you can test it on your machines if you have the docker running as well.

**Review by yordan-georgiev — APPROVED** [review]

**Pull request merged**
