### PR TITLE
feat: implemented yaml validation

### PR DESCRIPTION
**Pull request by Vasil-Derilov**
to test out the validator do

`cd src/python/tpl-gen`
`poetry install`
`SRC='/opt/csi/csi-infra-conf/sms' poetry run validate_yaml`

### CODE REVIEW

**Comment by Vasil-Derilov** [comment]
sorry for the many changes I forgot to turn off my formatter so it went ham on the existing code. Its the black-foramtter

**Review by yordan-georgiev — CHANGES_REQUESTED** [review]
remove the __pycache__ files

**Comment by Vasil-Derilov** [comment]
Canceling this merge request this functionality will be moved into csi-infra-conf. I will leave the branch so I can use it for referance.

**Comment by yordan-georgiev** [comment]
Yordan Georgiev

we MUST redefined the task.
Yordan Georgiev

the pydantic validation files should be per org-app-env environment
each step in the yaml file should have do_enforce_config_validation attribute
if the att is tru than a validator call in the conf project will verify that the config file of the yaml file’s step does pass the validation
this WILL enforce the configuration versioning we tried , but failed to achieve


it will take time to enforce the config validation for all the existing steps , but it will be worth it , because the updates of both the terraform code AND the configuration WILL be better managed ..
Yordan Georgiev
  [< 1 minute ago](https://flok-ws.slack.com/archives/D03GED56J87/p1679065033239419?thread_ts=1679062946.106839&cid=D03GED56J87)
this should also enable better “code fluidity” aka portability between the different projects .

**Pull request closed without merging**
